/**
 * @fileoverview Zustand store for the current patient intake session.
 * Tracks the intake workflow from welcome through summary, including
 * attendant status, captured documents, and the AI-generated summary.
 *
 * @module lib/stores/intake-store
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import type { IntakeSummary } from '@/lib/services/ai';

/** Steps in the intake workflow */
export type IntakeStep = 'welcome' | 'history' | 'conversation' | 'summary';

/** A document captured during intake (prescription photo, lab report, etc.) */
export interface CapturedDocument {
  /** Unique identifier */
  id: string;
  /** Type of document */
  type: 'prescription' | 'lab_report';
  /** Public URL of the uploaded image */
  imageUrl: string;
  /** Extracted data from AI processing, if completed */
  extractedData: Record<string, unknown> | null;
  /** Whether extraction is in progress */
  isProcessing: boolean;
  /** Timestamp of capture */
  capturedAt: Date;
}

/** Intake store state */
interface IntakeState {
  /** The current visit ID for this intake session */
  visitId: string | null;
  /** The registered patient this session belongs to */
  patientId: string | null;
  /** Whether the person doing intake is an attendant (not the patient) */
  isAttendant: boolean;
  /** Relationship of attendant to patient (e.g. "spouse", "parent") */
  attendantRelation: string | null;
  /** Documents captured during intake (prescriptions, lab reports) */
  capturedDocuments: CapturedDocument[];
  /** The structured intake summary generated by AI */
  intakeSummary: IntakeSummary | null;
  /** Current step in the intake workflow */
  step: IntakeStep;
}

/** Intake store actions */
interface IntakeActions {
  /**
   * Initialize a new intake session after registration.
   * Both IDs come from `registerAndStartVisit()` in services/registration.
   */
  startIntake: (visitId: string, patientId: string) => void;
  /** Set whether the speaker is an attendant */
  setAttendant: (isAttendant: boolean, relation?: string) => void;
  /** Add a captured document to the session */
  addDocument: (doc: CapturedDocument) => void;
  /** Update extraction results for a captured document */
  updateDocumentExtraction: (
    docId: string,
    extractedData: Record<string, unknown>
  ) => void;
  /** Mark a document as done processing */
  setDocumentProcessed: (docId: string) => void;
  /** Set the AI-generated intake summary */
  setIntakeSummary: (summary: IntakeSummary) => void;
  /** Advance to the next step in the workflow */
  nextStep: () => void;
  /** Go back to the previous step */
  previousStep: () => void;
  /** Set a specific step */
  setStep: (step: IntakeStep) => void;
  /** Reset the store to its initial state */
  reset: () => void;
}

/** Step progression order */
const STEP_ORDER: IntakeStep[] = ['welcome', 'history', 'conversation', 'summary'];

/** Initial state values */
const initialState: IntakeState = {
  visitId: null,
  patientId: null,
  isAttendant: false,
  attendantRelation: null,
  capturedDocuments: [],
  intakeSummary: null,
  step: 'welcome',
};

/**
 * Global intake session store.
 * Tracks the state of the current patient intake workflow.
 *
 * @example
 * ```tsx
 * function IntakeWizard() {
 *   const { step, nextStep, isAttendant } = useIntakeStore();
 *
 *   switch (step) {
 *     case 'welcome': return <WelcomeScreen />;
 *     case 'history': return <HistoryCapture />;
 *     case 'conversation': return <IntakeChat />;
 *     case 'summary': return <SummaryReview />;
 *   }
 * }
 * ```
 */
export const useIntakeStore = create<IntakeState & IntakeActions>()(
  persist(
    (set) => ({
  ...initialState,

  startIntake: (visitId, patientId) =>
    set({
      ...initialState,
      visitId,
      patientId,
      step: 'welcome',
    }),

  setAttendant: (isAttendant, relation) =>
    set({
      isAttendant,
      attendantRelation: relation ?? null,
    }),

  addDocument: (doc) =>
    set((state) => ({
      capturedDocuments: [...state.capturedDocuments, doc],
    })),

  updateDocumentExtraction: (docId, extractedData) =>
    set((state) => ({
      capturedDocuments: state.capturedDocuments.map((doc) =>
        doc.id === docId ? { ...doc, extractedData } : doc
      ),
    })),

  setDocumentProcessed: (docId) =>
    set((state) => ({
      capturedDocuments: state.capturedDocuments.map((doc) =>
        doc.id === docId ? { ...doc, isProcessing: false } : doc
      ),
    })),

  setIntakeSummary: (summary) =>
    set({ intakeSummary: summary }),

  nextStep: () =>
    set((state) => {
      const currentIndex = STEP_ORDER.indexOf(state.step);
      const nextIndex = Math.min(currentIndex + 1, STEP_ORDER.length - 1);
      return { step: STEP_ORDER[nextIndex] };
    }),

  previousStep: () =>
    set((state) => {
      const currentIndex = STEP_ORDER.indexOf(state.step);
      const prevIndex = Math.max(currentIndex - 1, 0);
      return { step: STEP_ORDER[prevIndex] };
    }),

  setStep: (step) => set({ step }),

  reset: () => set(initialState),
    }),
    {
      name: 'glyph-intake-session',
      /**
       * sessionStorage so a tablet refresh mid-intake doesn't lose the visit
       * (and closing the browser still clears it). Only session scalars are
       * persisted — documents/summary are refetchable.
       */
      storage: createJSONStorage(() => sessionStorage),
      partialize: (state) => ({
        visitId: state.visitId,
        patientId: state.patientId,
        isAttendant: state.isAttendant,
        attendantRelation: state.attendantRelation,
        step: state.step,
      }),
    }
  )
);
